# Generated by Django 3.2.9 on 2021-11-21 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descritivo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackSCI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=1000)),
                ('comportamento', models.CharField(max_length=1000)),
                ('impacto', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pilar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Reconhecimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='Reconhecimentos.feedback')),
                ('pilar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reconhecimentos.pilar')),
                ('reconhecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconhecedor', to=settings.AUTH_USER_MODEL)),
                ('reconhecido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconhecido', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
