# Generated by Django 3.2.9 on 2022-01-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconhecimentos', '0002_inclusao_dos_pilares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='descritivo',
            field=models.CharField(max_length=220),
        ),
    ]
