# Generated by Django 3.2.9 on 2021-11-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reconhecimentos', '0002_auto_20211121_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valor',
            name='descricoes',
        ),
        migrations.DeleteModel(
            name='DescricaoDoValor',
        ),
        migrations.DeleteModel(
            name='Valor',
        ),
    ]
