# Generated by Django 3.2.9 on 2022-01-11 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reconhecimentos', '0002_inclusao_dos_pilares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='descritivo',
            field=models.CharField(max_length=220),
        ),
        migrations.CreateModel(
            name='LOG_Ciclo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_da_modificacao', models.DateField(auto_now_add=True)),
                ('descricao_da_alteracao', models.CharField(max_length=50)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclo', to='Reconhecimentos.ciclo')),
                ('usuario_que_modificou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_que_modificou', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
