# Generated by Django 3.2.9 on 2022-03-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconhecimentos', '0003_ciclo_log_ciclo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='data_final',
            field=models.DateField(null=True),
        ),
    ]
