# Generated by Django 3.2.9 on 2022-01-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconhecimentos', '0003_auto_20220111_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_ciclo',
            name='data_da_modificacao',
            field=models.DateField(auto_now=True),
        ),
    ]
