# Generated by Django 3.2.12 on 2022-04-04 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reconhecimentos', '0004_alter_ciclo_data_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agradecimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now_add=True)),
                ('mensagem', models.CharField(max_length=1000)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador', to=settings.AUTH_USER_MODEL)),
                ('reconhecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconhecimento', to='Reconhecimentos.reconhecimento')),
            ],
        ),
    ]
