# Generated by Django 3.2.9 on 2022-01-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconhecimentos', '0004_alter_log_ciclo_data_da_modificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='nome',
            field=models.CharField(default='Nome Ciclo', max_length=25),
            preserve_default=False,
        ),
    ]
