# Generated by Django 3.2.12 on 2022-03-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconhecimentos', '0004_alter_ciclo_data_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='nome',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
