# Generated by Django 3.2.9 on 2022-01-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconhecimentos', '0004_auto_20220112_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='data_final',
            field=models.DateField(null=True),
        ),
    ]
