# Generated by Django 3.2.9 on 2022-02-09 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reconhecimentos', '0004_ciclo_log_ciclo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_ciclo',
            name='usuario_que_modificou',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_que_modificou', to=settings.AUTH_USER_MODEL),
        ),
    ]
