# Generated by Django 3.2.9 on 2022-01-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconhecimentos', '0005_ciclo_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_ciclo',
            name='data_final_alterada',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='log_ciclo',
            name='descricao_da_alteracao',
            field=models.CharField(max_length=63),
        ),
    ]
