# Generated by Django 3.2.9 on 2022-02-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconhecimentos', '0006_auto_20220126_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_ciclo',
            name='novo_nome_ciclo',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
