# Generated by Django 3.2.9 on 2022-02-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconhecimentos', '0008_log_ciclo_antigo_nome_ciclo'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_ciclo',
            name='antiga_data_final',
            field=models.DateField(default=None, null=True),
        ),
    ]
