# Generated by Django 3.2.9 on 2022-02-08 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reconhecimentos', '0009_log_ciclo_antiga_data_final'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log_ciclo',
            old_name='data_final_alterada',
            new_name='nova_data_final',
        ),
    ]
