# Generated by Django 3.2.9 on 2022-02-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reconhecimentos', '0010_rename_data_final_alterada_log_ciclo_nova_data_final'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log_ciclo',
            old_name='antiga_data_final',
            new_name='data_final_alterada',
        ),
        migrations.RemoveField(
            model_name='log_ciclo',
            name='nova_data_final',
        ),
    ]
