# Generated by Django 3.2.9 on 2022-02-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconhecimentos', '0011_auto_20220208_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_ciclo',
            name='nova_data_alterada',
            field=models.DateField(default=None, null=True),
        ),
    ]
