# Generated by Django 3.2.9 on 2022-02-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reconhecimentos', '0012_log_ciclo_nova_data_alterada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log_ciclo',
            old_name='data_final_alterada',
            new_name='antiga_data_final',
        ),
    ]
