# Generated by Django 3.2.9 on 2021-11-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
