# Generated by Django 3.2.9 on 2021-12-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_rename_usuario_no_slack_colaborador_usuario_id_do_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='ultima_apreciacao',
            field=models.DateField(null=True),
        ),
    ]
