# Generated by Django 3.2.9 on 2021-12-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_rename_usuario_no_slack_colaborador_usuario_id_do_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='quantidade_de_apreciacoes_recebidas',
            field=models.IntegerField(null=True),
        ),
    ]
