# Generated by Django 3.2.9 on 2022-02-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Login', '0002_rename_usuario_no_slack_colaborador_usuario_id_do_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='data_ultimo_reconhecimento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
