# Generated by Django 3.2.9 on 2021-12-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_colaborador_quantidade_de_apreciacoes_recebidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='quantidade_de_apreciacoes_recebidas',
        ),
    ]
