# Generated by Django 3.2.9 on 2022-01-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_remove_colaborador_quantidade_de_apreciacoes_recebidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='administrador',
            field=models.BooleanField(default=False),
        ),
    ]
