# Generated by Django 3.2.9 on 2022-02-21 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_auto_20220119_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOG_Administrador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_modificacao', models.DateField(auto_now=True)),
                ('descricao', models.CharField(max_length=50)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Administrador', to=settings.AUTH_USER_MODEL)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Colaborador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
