
# Generated by Django 3.2.12 on 2022-03-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_log_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_administrador',
            name='descricao',
            field=models.CharField(max_length=150),
        ),
    ]
