# Generated by Django 4.1.2 on 2023-11-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_alter_log_administrador_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='esta_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
