# Generated by Django 4.1.2 on 2023-11-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0009_colaborador_esta_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='usuario_id_do_chat',
        ),
    ]
